/* auto-generated by OHOS-RS */
/* eslint-disable */
import { NodeContent } from "@kit.ArkUI"

export interface ApplicationLifecycle {
  environmentCallback: EnvironmentCallback
  windowStageEventCallback: WindowStageEventCallback
}

export interface EnvironmentCallback {
  onConfigurationUpdated: () => void
  onMemoryLevel: () => void
}

export interface WindowStageEventCallback {
  onWindowStageCreate: () => void
  onWindowStageDestroy: () => void
  onAbilityCreate: () => void
  onAbilityDestroy: () => void
  onAbilitySaveState: () => void
}

export declare function init(slot: NodeContent): ApplicationLifecycle;

export declare function changeRender(index: number): void